//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGGIA
    {
        public int MASP { get; set; }
        public Nullable<double> GIABAN { get; set; }
        public Nullable<double> GIASAUKM { get; set; }
        public Nullable<System.DateTime> NGAYCAPNHAT { get; set; }
    }
}
