//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAPHANG
    {
        public int MACTPNH { get; set; }
        public int MAPHIEUNH { get; set; }
        public string USERNAME { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOLUONGNHAP { get; set; }
        public string DONVITINH { get; set; }
        public Nullable<int> SLTUNGDV { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public Nullable<double> THANHTIEN { get; set; }
    
        public virtual PHIEUNHAPHANG PHIEUNHAPHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
