//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUDATHANG
    {
        public int MACTPDH { get; set; }
        public int MAPHIEUDH { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> SOLUONGDAT { get; set; }
        public Nullable<double> GIANHAP { get; set; }
        public string DVT { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
    
        public virtual PHIEUDATHANG PHIEUDATHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
