//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
            this.PHIEUTRAHANGs = new HashSet<PHIEUTRAHANG>();
            this.THONGBAOs = new HashSet<THONGBAO>();
        }

        [NotMapped]
        public List<GIAOHANG> DHCollection { get; set; }
        public string MADH { get; set; }
        public string USERNAME { get; set; }
        public string DIACHI { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<System.DateTime> NGAYGIAO { get; set; }
        public Nullable<int> MAGIAOHANG { get; set; }
        public string SDTGIAO { get; set; }
        public Nullable<double> TONGTIEN { get; set; }
        public Nullable<bool> TINHTRANGTHANHTOAN { get; set; }
        public Nullable<int> MAPTTT { get; set; }
        public Nullable<double> PHISHIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        public virtual GIAOHANG GIAOHANG { get; set; }
        public virtual PTTHANHTOAN PTTHANHTOAN { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRAHANG> PHIEUTRAHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGBAO> THONGBAOs { get; set; }
    }
}
