//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTRAHANG
    {
        public string MAPHIEU { get; set; }
        public string USERNAME { get; set; }
        public string MADH { get; set; }
        public Nullable<int> MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<System.DateTime> NGAYTRA { get; set; }
        public string LYDO { get; set; }
        public string HINHANH { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
    }
}
