//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDHs = new HashSet<CHITIETDH>();
            this.CTPHIEUDATHANGs = new HashSet<CTPHIEUDATHANG>();
            this.CTPHIEUNHAPHANGs = new HashSet<CTPHIEUNHAPHANG>();
            this.SPTHICHes = new HashSet<SPTHICH>();
        }
    
        public int MASP { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public string TRONGLUONG { get; set; }
        public string THANHPHAN { get; set; }
        public string XUATXU { get; set; }
        public string CACHDUNG { get; set; }
        public Nullable<double> GIAGOC { get; set; }
        public string HINH { get; set; }
        public string PHANLOAI { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public Nullable<int> MANCC { get; set; }
        public Nullable<int> HANSUDUNG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> MUCKM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDH> CHITIETDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUDATHANG> CTPHIEUDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAPHANG> CTPHIEUNHAPHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual NHACC NHACC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPTHICH> SPTHICHes { get; set; }
    }
}
