//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebKhoaLuan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public string USERNAME { get; set; }
        public string MADH { get; set; }
        public int NOIDUNG { get; set; }
        public Nullable<System.DateTime> THOIGIAN { get; set; }
        public Nullable<bool> TRANGTHAIDOC { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual DONHANG DONHANG { get; set; }
    }
}
